# Integration modules for PRIMUM AI Sales Orchestration Platform
# Simulated credit bureau, CRM, and loan booking engines

from typing import Dict, Any, List
import uuid
from datetime import datetime


class CreditBureauAPI:
    """Simulated Credit Bureau API for retrieving credit scores and reports"""
    
    def __init__(self):
        # Predefined credit scores for demo purposes
        self.credit_database = {
            "aadhaar_1234": {"credit_score": 780, "history_length": 8, "accounts": 5},
            "pan_ABC1234P": {"credit_score": 750, "history_length": 6, "accounts": 3},
            "mobile_9876543210": {"credit_score": 720, "history_length": 5, "accounts": 4},
            "email_john.doe@example.com": {"credit_score": 690, "history_length": 4, "accounts": 2},
        }
    
    def get_credit_report(self, identifier: str, identifier_type: str = "mobile") -> Dict[str, Any]:
        """
        Simulate getting credit report from bureau
        identifier_type: 'mobile', 'email', 'aadhaar', 'pan'
        """
        # Find credit data based on identifier
        key = identifier
        
        # If not found directly, try to find matching record
        credit_record = None
        for db_key, record in self.credit_database.items():
            if identifier in db_key or key in db_key:
                credit_record = record
                break
        
        # If no record found, create a random one for demo
        if not credit_record:
            import random
            credit_record = {
                "credit_score": random.randint(650, 800),
                "history_length": random.randint(2, 10),
                "accounts": random.randint(1, 8),
            }
        
        # Add some variance to the score for realism
        variance = random.randint(-50, 50)
        credit_score = max(300, min(850, credit_record["credit_score"] + variance))
        
        return {
            "status": "success",
            "identifier": identifier,
            "identifier_type": identifier_type,
            "credit_score": credit_score,
            "credit_history_length_years": credit_record["history_length"],
            "total_accounts": credit_record["accounts"],
            "active_accounts": max(1, credit_record["accounts"] // 2),
            "credit_utilization_ratio": round(random.uniform(0.2, 0.6), 2),
            "recent_inquiries": random.randint(0, 3),
            "payment_history": "Good",
            "report_date": datetime.now().isoformat()
        }
    
    def simulate_delay(self):
        """Simulate API delay for more realistic behavior"""
        import time
        time.sleep(0.5)  # 500ms delay


class CRMIntegration:
    """Simulated CRM system for lead management"""
    
    def __init__(self):
        self.leads = {}
        self.activities = {}
    
    def create_lead(self, customer_data: Dict[str, Any]) -> Dict[str, Any]:
        """Create a new lead in CRM"""
        lead_id = f"LEAD-{str(uuid.uuid4())[:8].upper()}"
        
        lead_data = {
            "lead_id": lead_id,
            "customer_name": customer_data.get("name", "Unknown Customer"),
            "contact_info": {
                "mobile": customer_data.get("mobile", ""),
                "email": customer_data.get("email", "")
            },
            "loan_amount_requested": customer_data.get("loan_amount", 0),
            "source_channel": "AI_Sales_Bot",
            "status": "new",
            "assigned_to": "AI_System",
            "created_at": datetime.now().isoformat(),
            "updated_at": datetime.now().isoformat(),
            "custom_fields": {
                "credit_score": customer_data.get("credit_score", "N/A"),
                "employment_status": customer_data.get("employment_status", "N/A"),
                "city": customer_data.get("city", "N/A")
            }
        }
        
        self.leads[lead_id] = lead_data
        
        # Log activity
        self.log_activity(lead_id, "Lead Created", "New lead generated by AI Sales Bot")
        
        return lead_data
    
    def update_lead_status(self, lead_id: str, status: str, notes: str = "") -> Dict[str, Any]:
        """Update lead status"""
        if lead_id in self.leads:
            self.leads[lead_id]["status"] = status
            self.leads[lead_id]["updated_at"] = datetime.now().isoformat()
            
            # Log activity
            self.log_activity(lead_id, f"Status Updated to {status}", notes)
            
            return self.leads[lead_id]
        
        return {"error": "Lead not found"}
    
    def log_activity(self, lead_id: str, activity_type: str, description: str) -> Dict[str, Any]:
        """Log activity against a lead"""
        activity_id = f"ACT-{str(uuid.uuid4())[:8].upper()}"
        activity = {
            "activity_id": activity_id,
            "lead_id": lead_id,
            "activity_type": activity_type,
            "description": description,
            "performed_by": "AI_Sales_Bot",
            "timestamp": datetime.now().isoformat()
        }
        
        if lead_id not in self.activities:
            self.activities[lead_id] = []
        
        self.activities[lead_id].append(activity)
        
        return activity
    
    def get_lead(self, lead_id: str) -> Dict[str, Any]:
        """Retrieve lead information"""
        return self.leads.get(lead_id, {"error": "Lead not found"})
    
    def get_lead_activities(self, lead_id: str) -> List[Dict[str, Any]]:
        """Get activities for a specific lead"""
        return self.activities.get(lead_id, [])


class LoanBookingEngine:
    """Simulated Loan Booking Engine for finalizing loan applications"""
    
    def __init__(self):
        self.applications = {}
    
    def book_loan_application(self, application_data: Dict[str, Any]) -> Dict[str, Any]:
        """Book a loan application in the system"""
        application_id = f"APP-{str(uuid.uuid4())[:8].upper()}"
        sanction_id = f"SANC-{str(uuid.uuid4())[:8].upper()}"
        
        # Set up default loan terms
        loan_amount = application_data.get("loan_amount", 0)
        interest_rate = application_data.get("interest_rate", 10.5)
        tenure_months = application_data.get("tenure_months", 60)
        
        # Calculate EMI
        monthly_rate = interest_rate / 12 / 100
        emi = 0
        if loan_amount > 0 and monthly_rate > 0 and tenure_months > 0:
            emi = loan_amount * monthly_rate * ((1 + monthly_rate) ** tenure_months) / (((1 + monthly_rate) ** tenure_months) - 1)
        
        application = {
            "application_id": application_id,
            "sanction_id": sanction_id,
            "customer_data": {
                "name": application_data.get("customer_name", "Unknown Customer"),
                "mobile": application_data.get("mobile", ""),
                "email": application_data.get("email", ""),
                "identity": application_data.get("identity", {}),
            },
            "loan_details": {
                "loan_amount": loan_amount,
                "sanctioned_amount": application_data.get("sanctioned_amount", loan_amount),
                "interest_rate": interest_rate,
                "tenure_months": tenure_months,
                "emi_amount": round(emi, 2) if emi > 0 else 0,
                "processing_fee": application_data.get("processing_fee", loan_amount * 0.02),
                "loan_purpose": application_data.get("loan_purpose", "Personal"),
                "disbursement_method": application_data.get("disbursement_method", "Bank Transfer")
            },
            "terms_conditions": {
                "first_emi_date": self._calculate_first_emi_date(),
                "due_date_cycle": "Monthly",
                "grace_period_days": 5,
                "prepayment_allowed": True,
                "prepayment_terms": "After 6 months, no charges for up to 25% of outstanding per year"
            },
            "status": "sanctioned_pending_docs",
            "booking_date": datetime.now().isoformat(),
            "branch_code": application_data.get("branch_code", "HQ001"),
            "relationship_manager": application_data.get("relationship_manager", "AI_Assistant"),
            "next_steps": ["Submit remaining documents", "Sign agreement", "Schedule disbursal"]
        }
        
        self.applications[application_id] = application
        
        # Generate repayment schedule
        application["repayment_schedule"] = self._generate_repayment_schedule(application)
        
        return application
    
    def _calculate_first_emi_date(self) -> str:
        """Calculate the first EMI date (typically 1 month from booking)"""
        from datetime import timedelta
        first_emi = datetime.now() + timedelta(days=30)
        return first_emi.strftime("%Y-%m-%d")
    
    def _generate_repayment_schedule(self, application: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate repayment schedule"""
        emi_count = application["loan_details"]["tenure_months"]
        emi_amount = application["loan_details"]["emi_amount"]
        loan_amount = application["loan_details"]["loan_amount"]
        
        schedule = []
        balance = loan_amount
        
        for i in range(emi_count):
            # Simple calculation - in reality, this would be more complex
            interest_component = balance * (application["loan_details"]["interest_rate"] / 12 / 100)
            principal_component = emi_amount - interest_component
            
            # Adjust last payment to account for rounding differences
            if i == emi_count - 1:
                principal_component = balance
                emi_amount = principal_component + interest_component
            
            balance -= principal_component
            
            emi_date = datetime.now().replace(day=1) + timedelta(days=30*(i+1))
            
            schedule.append({
                "emi_number": i + 1,
                "due_date": emi_date.strftime("%Y-%m-%d"),
                "emi_amount": round(emi_amount, 2),
                "principal_component": round(principal_component, 2),
                "interest_component": round(interest_component, 2),
                "outstanding_balance": round(balance, 2),
                "status": "pending"
            })
        
        return schedule
    
    def update_application_status(self, application_id: str, status: str, remarks: str = "") -> Dict[str, Any]:
        """Update application status"""
        if application_id in self.applications:
            self.applications[application_id]["status"] = status
            self.applications[application_id]["updated_at"] = datetime.now().isoformat()
            
            return self.applications[application_id]
        
        return {"error": "Application not found"}
    
    def get_application(self, application_id: str) -> Dict[str, Any]:
        """Retrieve application details"""
        return self.applications.get(application_id, {"error": "Application not found"})


# Example usage
if __name__ == "__main__":
    # Test the credit bureau API
    credit_api = CreditBureauAPI()
    credit_report = credit_api.get_credit_report("9876543210", "mobile")
    print("Credit Report:", credit_report)
    
    # Test CRM integration
    crm = CRMIntegration()
    customer_data = {
        "name": "John Doe",
        "mobile": "9876543210",
        "email": "john.doe@example.com",
        "loan_amount": 2000000,
        "credit_score": 750,
        "employment_status": "salaried",
        "city": "Mumbai"
    }
    lead = crm.create_lead(customer_data)
    print("Created Lead:", lead)
    
    # Test loan booking engine
    loan_engine = LoanBookingEngine()
    application_data = {
        "customer_name": "John Doe",
        "mobile": "9876543210",
        "email": "john.doe@example.com",
        "loan_amount": 2000000,
        "interest_rate": 10.5,
        "tenure_months": 60,
        "processing_fee": 40000,
        "loan_purpose": "Home Renovation",
    }
    application = loan_engine.book_loan_application(application_data)
    print("Booked Application:", application)